import type { AnnualGoal, QuarterlyGoal, WeeklyTask, WeeklyReviewData, LifeGoal } from '../types';

// Sample data to demonstrate the Personal OS system
export const sampleData = {
  annualGoals: [
    {
      id: 'annual-1',
      type: 'annual' as const,
      title: 'Achieve Stanford AI Certificate',
      description: 'Complete the Stanford AI Professional Certificate program to build foundational knowledge in artificial intelligence and machine learning.',
      category: 'Learning & Development',
      priority: 'high' as const,
      status: 'in-progress' as const,
      createdAt: new Date('2025-01-01'),
      targetDate: new Date('2025-12-31'),
      progress: 35,
      year: 2025,
      quarterlyGoals: ['quarterly-1', 'quarterly-2'],
    },
    {
      id: 'annual-2',
      type: 'annual' as const,
      title: 'Launch Internal AI Pilot Project',
      description: 'Design and implement an AI pilot project within the organization to demonstrate practical applications and ROI of AI technology.',
      category: 'Career & Leadership',
      priority: 'high' as const,
      status: 'in-progress' as const,
      createdAt: new Date('2025-01-01'),
      targetDate: new Date('2025-11-30'),
      progress: 25,
      year: 2025,
      quarterlyGoals: ['quarterly-3'],
    },
    {
      id: 'annual-3',
      type: 'annual' as const,
      title: 'Build Thought Leadership Brand',
      description: 'Establish myself as a thought leader in AI and digital transformation through content creation and professional networking.',
      category: 'Personal Branding',
      priority: 'medium' as const,
      status: 'in-progress' as const,
      createdAt: new Date('2025-01-01'),
      targetDate: new Date('2025-12-31'),
      progress: 20,
      year: 2025,
      quarterlyGoals: ['quarterly-4'],
    },
  ] as AnnualGoal[],

  quarterlyGoals: [
    {
      id: 'quarterly-1',
      type: 'quarterly' as const,
      title: 'Complete Stanford AI Fundamentals',
      description: 'Complete modules 1-4 of the Stanford AI course focusing on machine learning fundamentals and neural networks.',
      category: 'Learning & Development',
      priority: 'high' as const,
      status: 'in-progress' as const,
      createdAt: new Date('2025-07-01'),
      targetDate: new Date('2025-09-30'),
      progress: 65,
      quarter: 3 as const,
      year: 2025,
      annualGoalId: 'annual-1',
      keyResults: [
        {
          id: 'kr-1',
          description: 'Complete all 4 course modules',
          targetValue: 4,
          currentValue: 2,
          unit: 'modules',
          completed: false,
        },
        {
          id: 'kr-2',
          description: 'Score 85%+ on all assignments',
          targetValue: 85,
          currentValue: 82,
          unit: '%',
          completed: false,
        },
        {
          id: 'kr-3',
          description: 'Complete practice projects',
          targetValue: 6,
          currentValue: 4,
          unit: 'projects',
          completed: false,
        },
      ],
      weeklyTasks: ['task-1', 'task-2'],
    },
    {
      id: 'quarterly-2',
      type: 'quarterly' as const,
      title: 'Network with AI Professionals',
      description: 'Build professional relationships with AI practitioners and thought leaders in the industry.',
      category: 'Networking',
      priority: 'medium' as const,
      status: 'in-progress' as const,
      createdAt: new Date('2025-07-01'),
      targetDate: new Date('2025-09-30'),
      progress: 40,
      quarter: 3 as const,
      year: 2025,
      annualGoalId: 'annual-1',
      keyResults: [
        {
          id: 'kr-4',
          description: 'Conduct coffee chats with directors',
          targetValue: 6,
          currentValue: 2,
          unit: 'meetings',
          completed: false,
        },
        {
          id: 'kr-5',
          description: 'Attend AI meetups/conferences',
          targetValue: 4,
          currentValue: 1,
          unit: 'events',
          completed: false,
        },
      ],
      weeklyTasks: ['task-3'],
    },
  ] as QuarterlyGoal[],

  weeklyTasks: [
    {
      id: 'task-1',
      title: 'Complete Module 2 of Stanford AI course',
      description: 'Focus on linear algebra fundamentals and neural network basics. Review prerequisites first.',
      quarterlyGoalId: 'quarterly-1',
      priority: 'high' as const,
      estimatedHours: 8,
      actualHours: 6,
      completed: false,
      weekOf: new Date('2025-09-15'),
      roadblocks: ['Linear algebra concepts more challenging than expected', 'Need to review fundamentals before proceeding'],
      notes: 'Making good progress but realized I need stronger math foundation',
    },
    {
      id: 'task-2',
      title: 'Practice project: Image classification',
      description: 'Build a simple image classification model using TensorFlow as practice for the course.',
      quarterlyGoalId: 'quarterly-1',
      priority: 'medium' as const,
      estimatedHours: 4,
      actualHours: 3,
      completed: true,
      weekOf: new Date('2025-09-15'),
      roadblocks: [],
      notes: 'Successfully implemented basic CNN model',
    },
    {
      id: 'task-3',
      title: 'Coffee chats with Finance and Operations directors',
      description: 'Schedule and conduct strategic conversations about AI opportunities in their departments.',
      quarterlyGoalId: 'quarterly-2',
      priority: 'high' as const,
      estimatedHours: 3,
      actualHours: 2.5,
      completed: true,
      weekOf: new Date('2025-09-15'),
      roadblocks: [],
      notes: 'Great insights gained, especially from Ops director about pilot project opportunities',
    },
  ] as WeeklyTask[],

  weeklyReviews: [
    {
      id: 'review-1',
      weekOf: new Date('2025-09-15'),
      completedTasks: ['task-2', 'task-3'],
      roadblocks: [
        'Knowledge Gap: My linear algebra is rustier than I thought. Trying to push through the Stanford material without reviewing the fundamentals is inefficient and frustrating.',
        'Energy Management: By Friday evening, I was too mentally drained to think creatively about the LinkedIn article. It was my lowest priority, so it was the first thing to get dropped.',
      ],
      learnings: [
        'The Operations director gave me a fantastic idea for the internal AI pilot project focusing on supply chain optimization.',
        'I need to block time for math review before diving into complex AI concepts.',
        'Coffee chats are incredibly valuable for building strategic relationships and gathering insights.',
      ],
      nextWeekPriorities: [
        'Priority 1 (Academic): Review linear algebra basics for 90 minutes on Tuesday, then complete Module 2 of the Stanford course by Friday.',
        'Priority 2 (Professional): Capitalize on the momentum from my coffee chat. Spend one hour on Wednesday drafting the one-page concept note for the AI pilot project based on the Ops director\'s idea.',
        'Priority 3 (Branding): Break down the article task. Spend just 30 minutes on Thursday morning writing the first two paragraphs of the LinkedIn article.',
      ],
      lastWeekGoals: [
        'Complete Module 2 of the Stanford AI course',
        'Conduct the two scheduled "coffee chats" with directors in Finance and Operations',
        'Create the outline for the first LinkedIn article',
      ],
      lastWeekResults: [
        '70% done. I got stuck on the linear algebra concepts and lost momentum.',
        'Done. Both were incredibly insightful. The Ops director gave me a fantastic idea for the internal AI pilot project.',
        'Not started. I ran out of time and energy after focusing on the Stanford course.',
      ],
      strategicCheckIn: 'These priorities directly address my Q3 Key Results. Priority #1 unblocks my Stanford progress. Priority #2 starts the work on the AI pilot project. Priority #3 gets the LinkedIn article started, which is a key branding goal.',
      overallProgress: 67,
      energyLevel: 3,
      satisfaction: 4,
      notes: 'Good week overall. Need to be more strategic about energy management and math prerequisites.',
    },
  ] as WeeklyReviewData[],

  lifeGoals: [
    {
      id: 'life-1',
      type: 'life' as const,
      title: 'Become an AI Technology Leader',
      description: 'Build expertise in artificial intelligence and machine learning to lead innovative projects and mentor others in the field.',
      vision: 'To be recognized as a thought leader in AI, speaking at conferences, publishing insights, and driving strategic AI initiatives that create meaningful impact.',
      category: 'Career' as const,
      timeframe: 'ten-year' as const,
      priority: 'high' as const,
      status: 'in-progress' as const,
      createdAt: new Date('2025-01-01'),
      targetDate: new Date('2035-01-01'),
      progress: 15,
      annualGoals: ['annual-1', 'annual-2'],
    },
    {
      id: 'life-2',
      type: 'life' as const,
      title: 'Achieve Financial Independence',
      description: 'Build a diversified investment portfolio and passive income streams to achieve financial freedom and security.',
      vision: 'To have the financial freedom to pursue meaningful work and experiences without being constrained by economic necessity.',
      category: 'Finance' as const,
      timeframe: 'ten-year' as const,
      priority: 'high' as const,
      status: 'in-progress' as const,
      createdAt: new Date('2025-01-01'),
      targetDate: new Date('2035-01-01'),
      progress: 25,
      annualGoals: [],
    },
    {
      id: 'life-3',
      type: 'life' as const,
      title: 'Master Creative Writing',
      description: 'Develop storytelling skills and publish meaningful written works that inspire and connect with readers.',
      vision: 'To publish a novel that touches peoples lives and contributes to important conversations about technology and humanity.',
      category: 'Creativity & Passion' as const,
      timeframe: 'five-year' as const,
      priority: 'medium' as const,
      status: 'not-started' as const,
      createdAt: new Date('2025-01-01'),
      targetDate: new Date('2030-01-01'),
      progress: 0,
      annualGoals: [],
    },
  ] as LifeGoal[],
};

export function loadSampleData() {
  const storageKey = 'personalos-data';
  const existingData = localStorage.getItem(storageKey);
  
  if (!existingData) {
    const data = {
      annualGoals: sampleData.annualGoals,
      quarterlyGoals: sampleData.quarterlyGoals,
      weeklyTasks: sampleData.weeklyTasks,
      weeklyReviews: sampleData.weeklyReviews,
      lifeGoals: sampleData.lifeGoals,
      activityLogs: [],
      currentYear: 2025,
      currentQuarter: 3 as const,
    };
    
    localStorage.setItem(storageKey, JSON.stringify(data));
    return data;
  }
  
  return null;
}
